### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by DesweR** [Skulltrail192/One-Core-Api#1]
Could you publish binaries?
Thanks.

**Comment by FranceBB** [comment]
I would love binaries as well.
As to the internal dlls, would compiling them with anything greater than SSE2 give any benefits?
I was thinking about AVX2.
Thank you in advance.

**Comment by dsp2003** [comment]
I also would like to know if binaries are going to be released. Compiling on your own is a non-trivial task and requires tons of patience, it's easy to mess up.

**Comment by byaka** [comment]
+1, need binaries!

**Comment by byaka** [comment]
Finded binaries [here](http://shorthornproject.com/allcategories.html?tab=onecore&item=item-onecore), but how to correctly install this?

**Comment by Skulltrail192** [comment]
Yes, i forget add link on Readme. Now we can download binaries

**Comment by DibyaTheXPFan** [comment]
BInery needs update

**Comment by r57zone** [comment]
@Skulltrail192 Can make an installer or bat a file for automatic installation?

**Comment by dsp2003** [comment]
@r57zone See here (in the "Packages" sub-directories): https://github.com/Skulltrail192/One-Core-API-Binaries

**Comment by r57zone** [comment]
@dsp2003, would like the fully automatic installer.

**Comment by dsp2003** [comment]
I would like the one that actually works and does not render the system unbootable. Automatic or not.

**Comment by Skulltrail192** [comment]
I think it is solved, close the issue
