### ISSUE TITLE
Possible code typo

### ISSUE THREAD

**Issue by pachuco** [Skulltrail192/One-Core-Api#13]
https://github.com/Skulltrail192/One-Core-Api/blob/master/dll/wrappers/base/gdi32_wrapper/d3dkmt.c#L268

bmpInfo->bmiColors[i].rgbGreen is assigned to twice from green, then blue.
I am pretty sure this is a typo.

**Comment by Skulltrail192** [comment]
Fixed on last commit, please see develop branch
