### ISSUE TITLE
OneDrive for XP/2003

### ISSUE THREAD

**Issue by pithwz** [Skulltrail192/One-Core-Api#17]
Hi,
Please add following APIS to run OneDrive(syncengine.dll), on XP/2003:

**kernel32:**
FindFirstFileNameW
FindNextFileNameW

**printui**
PrintUIDownloadAndInstallLegacyDriver
ShowHelpLinkDialog
SetActiveDefaultMode

**apphelp**
SdbQueryFlagMask
SdbGetMatchingExe

**Comment by Skulltrail192** [comment]
Same issue on One-Core-API Binaries:

https://github.com/Skulltrail192/One-Core-API-Binaries/issues/19

This issue will be closed.
