### ISSUE TITLE
UEFI boot support

### ISSUE THREAD

**Issue by DibyaTheXPFan** [Skulltrail192/One-Core-Api#26]
Freeloader of Reactos on xp . Is it possible?

**Comment by Skulltrail192** [comment]
For now, i think freeldr doesn't support UEFI

**Comment by mittorn** [comment]
What about quibble?
https://github.com/maharmstone/quibble
But UEFI likely to cause driver incompatibilities

**Comment by jonm58** [comment]
https://github.com/pbatard/uefi-ntfs
https://github.com/pbatard/efifs

**Comment by Skulltrail192** [comment]
Well, next version of One-Core-API Binaries will allow install on UEFI with CSM support. I need more tests to get UEFI with GOP

**Comment by Skulltrail192** [comment]
It's done on Version 3.0.0, by Modern Setup Installer package and One-Core-API tools.

See: https://github.com/Skulltrail192/One-Core-API-Tools
