### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by zamadatix** [Skulltrail192/One-Core-Api#27]
I can't seem to find a guide for how to install any of this. I have an XP 64 bit machine with all of the latest updates, now what do I do? Just copy the one core api binary files over and reboot? How do I know it's installed and working after that?

Thanks!

**Comment by Sheepsnoop** [comment]
Here's a tutorial I followed:
go to packages x64 and don't use the release that's there because that is outdated.

order is: Base-Kernel-NewDlls-AppCompat-ShellUpdate-API-SET-[Reboot]-D3D.
then copy NTEXT.DLL to VTDLL.DLL
(i.e. C:\Windows\System32\NTEXT.DLL -> C:\Windows\System32\VTDLL.dll
and C:\Windows\SysWOW64\NTEXT.DLL -> C:\Windows\SysWOW64\VTDLL.dll if you're on x64)

**Comment by zamadatix** [comment]
Thanks for the information, I think I'm definitely closer than I was before. I ran the installers in that order and "canceled" out of the Windows File Protection dialogs but at the reboot step I think the files were still replaced. Is there something I have to do to disable Windows File Protection first?

**Comment by r3muxd** [comment]
To disable SFC, follow https://msfn.org/board/topic/110834-disable-xp-sfcwfp-works-with-sp3/, and replace sfcfiles.dll with this one.
[sfcfiles.zip](https://github.com/Skulltrail192/One-Core-Api/files/2939082/sfcfiles.zip)
Then use XPLite free to disable SFC.

**Comment by zamadatix** [comment]
Thanks r3muxd. Unfortunately that guide doesn't directly apply to XP x64 as DEBUG is a 16 bit program. I was able to take that guide and previous information from this thread to come up with the below install guide for XP 64 bit that seems to have worked!

1. Open services.msc. Find the "Cryptographic Services" entry, set it to disabled on startup, then stop the service.
2. Run the following commands in command prompt, lines starting with "rem" are comments:

cd \windows\system32
ren rshx32.dll rshx32.old
ren sfc_os.dll sfc_os.old
cd \

rem If upon running the following 2 commands Windows File Protection warnings show up stop and disable the cryptographic service again and retry from the del commands

del rshx32.dll /s
del sfc_os.dll /s
cd \windows\system32
copy rshx32.old rshx32.dll
copy sfc_os.old sfc_os.dll

3. Hex editing procedure. Download HxD from https://mh-nexus.de/en/programs.php
- Open rshx32.dll
- Ctrl+F to search for the hex code "74 00 5C 00 4F"
- Replace "5C" in the middle with "00"
- Repeat the above steps for sfc_os.dll


4. Return to the command prompt window and run:

copy rshx32.dll dllcache
copy sfc_os.dll dllcache

3. Open Regedit to "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SafeBoot", create a new DWORD named "OptionValue" and set its value to "1"
4. In services.msc re-enable "Cryptographic Services" for startup but do not start the service.
5. Reboot
6. Download https://github.com/Skulltrail192/One-Core-API-Binaries/tree/master/Packages/x64
7. Run the installers in /x64/<component>/update/update.exe in the order Base, Kernel, New Dlls, App Compat, Shell Update, API-SET, (reboot), D3D.
8. Run the following in command prompt:
copy C:\Windows\System32\NTEXT.DLL C:\Windows\System32\VTDLL.dll
copy C:\Windows\SysWOW64\NTEXT.DLL C:\Windows\SysWOW64\VTDLL.dll
9. Reboot

**Comment by r3muxd** [comment]
The sfcfiles.dll patch should work. Try copying it into system32 and
syswow64.
I recommend doing both, in case you install an update that replaces one,
and because even if SFC comes back online, the sfcfiles patch will tell it
to do virtually nothing.

**Comment by jb3441** [comment]
how about the kernel standalone
will gonna install it?

**Comment by LazytownSpo666** [comment]
> how about the kernel standalone will gonna install it? and cant startup after shell update was installed

did you installed it correctly?

**Comment by andika207** [comment]
this install guide is totally useless. I can't find any of those folders and what I do have to install

the main main page is also absolete as it's not been updated for ages.

**Comment by jonm58** [comment]
> 这个安装指南完全没用。 我找不到任何这些文件夹以及我必须安装的内容
> 
> 主页面也已过时，因为它已经很久没有更新了。

https://github.com/Skulltrail192/One-Core-Api-Binaries

**Comment by Skulltrail192** [comment]
This repository is the source code and you can compile using Reactos's build enviroment for Visual Studio. And you install the binaries (final product) follow this Readme:

https://github.com/Skulltrail192/One-Core-API-Binaries

And see the releases:
https://github.com/Skulltrail192/One-Core-API-Binaries/releases
