### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by KOLANICH** [Skulltrail192/One-Core-Api#3]
Can you document this?
I have looked into the docs in the git repo a bit but it seems they are not about onecoreapi.
I wonder:
1 Do we really need all these files in the repo? I saw lot of folders which seem to be unneeded for this project.
2 Do you use Microsoft Windows Application Compatibility Toolkit? Why don't you use it if you don't?
3 How to build it? I guess something like ```cmake && make``` but there should be a relevant doc.

**Comment by KOLANICH** [comment]
1 Is it possible to move everything unneeded to build the tool (tests, reactos residuals, etc) into a separate git repo? I mean that it'd be nice to have a repo where you shouldn't guess if you shouldn't waste your time on reading that file because that file is only relevant to reactos (I'm going to use it on XP, not in reactos).
2 for hooking. The thing was designed to automatically hook the apps. So you don't need a completely new kernel32.dll, you can make apps use wjndows one if it is compatible and a your shim if it isn't.
3 Do you have dedicated docs for your project?

**Comment by Skulltrail192** [comment]
1. Is possible, but, need time and i don't have now.
2. Well, i'm analysing this porpouse, in fact, x64 version already make it.
3. For now, no, i don't have time.

**Comment by dsp2003** [comment]
Is there a quick instruction how to set this up? I can't figure out how this is supposed to work. For example, what steps do I have to take to make, for example, Palemoon 27.x to work under Windows XP? Should I patch the Palemoon's executable with HEX editor to force it to load wrapper libraries?

If the instructions are not available, an automatic installer (possibly, NSIS script or some kind of batch CMD script) would be much appreciated.

**Comment by Skulltrail192** [comment]
Well, One-Core-API is projeted to work only repleacing System files and running applications like native version. Also avaliable on One-Core-API a compatibility slayer with Vista+ layers. You can see on: 
shorthornproject.com, on "Shorthorn Packs" section

**Comment by dsp2003** [comment]
Unfortunately, your ADrive account was taken down with all of your files. :(
