### ISSUE TITLE
Bug while trying to run some NET 2.0 applications

### ISSUE THREAD

**Issue by blueclouds8666** [Skulltrail192/One-Core-Api#31]
I installed One-Core API Base on my Windows XP SP3 Professional partition. It ran great but i found that a couple programs didn't want to run anymore, specially .NET 2.0 ones. I've seen it happening with Unigine Sanctuary and other Unigine benchmark applications, and here's the shown error:
![image](https://user-images.githubusercontent.com/52018385/96778630-3ce85200-13ec-11eb-86ac-4a32a3e39173.png)

Also cheat engine had a minor render issue with a dialog screen:
![image](https://user-images.githubusercontent.com/52018385/96778713-55586c80-13ec-11eb-8973-c3631554df55.png)

I downloaded and installed the latest binaries from here: https://github.com/Skulltrail192/One-Core-API-Binaries
Beside those two annoyances, One-Core ran pretty good and i'm impressed by the results. keep it up with this great project

**Comment by blueclouds8666** [comment]
after testing the new 2.0 release, i can confirm this issue has been fixed. NET2 based applications now run fine

**Comment by NEO-SPECTRUMAN** [comment]
> 
> 
> after testing the new 2.0 release, i can confirm this issue has been fixed. NET2 based applications now run fine

how you install 2.0 binaries?
i'm only bricked XP
and broke preinstalled OCAPI 1.1 on ncore (sv2003)
