### ISSUE TITLE
Need help to compile

### ISSUE THREAD

**Issue by cesar300** [Skulltrail192/One-Core-Api#36]
I want to compile this and I have a few problems:
- I have installed visual studio 2010 and executed configure.cmd from the visual studio command line.
- When I type ninja from the output folder I got several errors which prevents compile continue.
 Cannot open include file 'propsys.h'. No such file or directory
and maybe others.
So the question is: How to compile this? A video tutorial would be nice.
Thanks

**Comment by cesar300** [comment]
I tried to use make, but I got this error:

[  2%] Linking C executable freeldr_pe.exe
[  2%] Built target freeldr_pe
Scanning dependencies of target setupldr
[  2%] Generating frldr16.bin.o
[  2%] Generating frldr16.bin
[  2%] Generating setupldr.sys
mingw32-make.exe[2]: *** [boot\freeldr\freeldr\CMakeFiles\setupldr.dir\build.mak
e:81: boot/freeldr/freeldr/setupldr.sys] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:32028: boot/freeldr/freeldr/CMake
Files/setupldr.dir/all] Error 2
mingw32-make.exe: *** [makefile:103: all] Error 2

Total Build Time: 00:05:43

Any help?

**Comment by wangwenx190** [comment]
I'm using the latest version of VS2019 but I also failed to build this project. When building this project, many subprojects can't be compiled and I got many compilation errors such as "can't define internal function", "can't recognize XXX". And it's only reliable to using the makefile generator and msbuild generator, other generators such as ninja will fail very quick at the beginning of compilation. I've tried many times of differrent build configurations, I even tried the ReactOS BE, but no one can build successfully. I think the repo owner really should provide a compilation instruction.

**Comment by wangwenx190** [comment]
MSVC doesn't compile, so I tried different builds of MinGW, but the result is the same, all compilers can't build this project successfully

**Comment by Skulltrail192** [comment]
Hello, try again. I use VS Studio 2012.

**Comment by Svyatpro** [comment]
1. Use RosBE 2.1.6 not newer.
2. Use MSVC 2012 (2010 and newer may work too)
3. Use "configure VSSolution" to build solution
4. Compile wrappers using solution (Debug only)

**Comment by Skulltrail192** [comment]
> 1. Use RosBE 2.1.6 not newer.
> 
>     2. Use MSVC 2012 (2010 and others may work too)
> 
>     3. Use "configure VSSolution" to build solution
> 
>     4. Compile wrappers using solution (Debug only)

Thanks my friend, now, this will closed.
