### ISSUE TITLE
Please don't store binaries in repos if you don't use git lfs for them

### ISSUE THREAD

**Issue by KOLANICH** [Skulltrail192/One-Core-Api#4]

**Comment by KOLANICH** [comment]
I don't see it fixed ...

**Comment by Skulltrail192** [comment]
What do you want me to do?

**Comment by KOLANICH** [comment]
Put all the binaries into LFS and push rewriting the history. This can probably be done using https://github.com/bozaro/git-lfs-migrate  (I have not used this myself so I don't know how well it works).
