### ISSUE TITLE
Intel HD Audio Drivers for Windows XP/Server 2003

### ISSUE THREAD

**Issue by creeper451** [Skulltrail192/One-Core-Api#45]
Hi, The other day i found my old laptop and decided to turn it into a retro machine so i installed Windows XP on it and managed to get all the drivers working expect for the "High Definition Audio" which is only supported on vista and higher so i was wondering could you support it on XP.
P.S Thanks for this amazing work 👍.

**Comment by Leandro2905** [comment]
Did you try the old drivers?
