### ISSUE TITLE
Feature request: Add string localizations from localized versions of Windows XP

### ISSUE THREAD

**Issue by Dobby233Liu** [Skulltrail192/One-Core-Api#48]
This would be nice to users that use the system in a language other than English, particularly Simplified Chinese, it feels irritating to see English everywhere in a Chinese system. Of course, I'm assuming that this is even possible; I'm quite curious if it actually is or not.

**Comment by Dobby233Liu** [comment]
> The unique language on binaries for now is English. You can install on Windows with another language, however, several dialogs and strings will be displayed in engilsh;
Oh, I see you are actually planning to do so

**Comment by Skulltrail192** [comment]
For now, i cant made for other languages. I have a lot things to do and to fix.
