### ISSUE TITLE
Is it work correctly in virtualbox?

### ISSUE THREAD

**Issue by byaka** [Skulltrail192/One-Core-Api#5]
I have winXP in vbox. How to correctly install to it?
For example vbox has special version of wined3d.dll for supporting 3d-accel.

**Comment by Skulltrail192** [comment]
Hello byaka, well, i'm working to get full compatibiliy with XP and i'm restructuring kernel32 wrapper, for now, maybe not work.

One-Core-API binaries has a wined3d version with support to Dx10 and Dx11. Please see oficial site on Readme and get lastest binaries

**Comment by Skulltrail192** [comment]
Next release of D3D runtime will redirect to d3dwine instead wind3d, without problem with virtual box additions.

**Comment by byaka** [comment]
good news, ty!

**Comment by Skulltrail192** [comment]
Now last commit fix it
