### ISSUE TITLE
Where is the file xpspkernel32.dll comes from?

### ISSUE THREAD

**Issue by Thompson-NO3** [Skulltrail192/One-Core-Api#50]
I noticed that I can not find the source code of xpspkernel32.dll, where does it come from?
Have you released all the source code?

**Comment by NEO-SPECTRUMAN** [comment]
original version of kernel32?

**Comment by Skulltrail192** [comment]
Windows XP native's kernel32.

**Comment by Thompson-NO3** [comment]
Are you sure? I mean this file https://github.com/Skulltrail192/One-Core-API-Binaries/blob/master/Packages/x86/Base%20Installer/XPSP3/xpspkernel32.dll.
It comes from en_winxp...iso?
Its version is 5.1.2600.16384, normally xp does not have this kind of version, should be 5.1.2600.5512 or sth like this

**Comment by jonm58** [comment]
emm,OCAPI all dlls come with 16384, perhaps for the sake of a uniform version number?

**Comment by Thompson-NO3** [comment]
I compare xpsp3's kernel32.dll and found a lot of diffs, so do you modify this file using some tools or recompile it?
There are many dlls within XPSP3 folder, they don't share the same version number.

**Comment by jonm58** [comment]
Maybe using some tools.

**Comment by NEO-SPECTRUMAN** [comment]
may it be from last posready updates?

**Comment by Skulltrail192** [comment]
What is the point or relevance about this question?
