### ISSUE TITLE
Virtual Box mouse doesn't work when Guest Additions is installed. 

### ISSUE THREAD

**Issue by yangu-hury** [Skulltrail192/One-Core-Api#51]
Virtual Box mouse doesn't work when Guest Additions and One Core API are installed at the same time. Alone both work fine. 

Virtual Box Version 5.2.44 r139111 (Qt5.6.2)

**Comment by NEO-SPECTRUMAN** [comment]
I used VirtualBox-5.2.44-139111 with ocapi long time

**Comment by yangu-hury** [comment]
> I used VirtualBox-5.2.44-139111 with ocapi long time without any problems with mouse and guest additions
> 
> now i'm using VirtualBox-4.2.0-80737 that has moar stable direct3d support on XP
> 
> (but i'm doesn't tested latest ocapi yet)

Well. I'm using this binaries from GitHub on a Original XP. Can you explain me the difference between these projects, LongHorn and ShortHorn.  I believe you are using these and not these One Core API bin over Original XP.

**Comment by Skulltrail192** [comment]
Fixed on One-Core-API Binaries.
