### ISSUE TITLE
BSOD after installing one-core-api (Windows XP SP3 crash)

### ISSUE THREAD

**Issue by Cixert** [Skulltrail192/One-Core-Api#53]
Hello, After installing I have received BSOD when rebooting the Windows XP SP3 system.
STOP: 0x0000008E (...)
Luckily I was able to reboot into safe mode, uninstalled one-core-api and Windows started again.

To install I have followed some instructions that I have seen on a website in Spanish.
https://www.genbeta.com/windows/this-hack-has-managed-to-run-modern-windows-xp-applications-so-you-can-use-it-chrome-102

It says:
1-Convert XP to Windows embedded and apply Windows update
(I understand that this step is not necessary and I have not done it)
2-Paste the Windows Vista dll oleacc.dll into system32
I have done it, is it necessary?
3-On this website I have seen an order to install the APIs. You show another order in your instructions. Neither of these is possible. what is the correct order?

Genbeta spanish web:
Base Installer > New Installer (Additional DLLs) > D3d Installer > API-SET Installer > App Compat > Kernel Update.
Is there or isn't there an experimental kernel update? I do not see it.

Skulltrail192
Installation order of packages:

App Compat only: This package can be installed without any other packages;

Base first: Base-> D3d -> API-SET -> Driver Update -> App Compat-> Additional Dlls;

AppCompat first: App Compat -> Base -> Driver Update -> D3d -> API-SET -> Additional Dlls.

If I try to install D-3-d before API-SET, it gives an error and tells API-SET to be installed before.

**Comment by Skulltrail192** [comment]
Give me the iso utilized. And i recommend creeate this issue on one-core-api **binaries**

**Comment by Cixert** [comment]
The last version 2.10
Ok, I Open issue on one-core-api-binaries
