### ISSUE TITLE
SysInternals ProcessExplorer is broken when run in the OS with One-Core-API installed

### ISSUE THREAD

**Issue by KOLANICH** [Skulltrail192/One-Core-Api#58]

**Comment by Skulltrail192** [comment]
I think is better create this issue on One-Core-API Binaries Project.

**Comment by Smu1zel** [comment]
> I think is better create this issue on One-Core-API Binaries Project.

Yes, it's been reported there as https://github.com/Skulltrail192/One-Core-API-Binaries/issues/164. Might be cleaner to close this one and continue the conversation there instead of having duplicate bug reports.

**Comment by KOLANICH** [comment]
I don't remember what was the problem, but this issue is about Sysinternals Process Explorer, not Process Hacker. I also don't understand why it should be filed against binaries repo rather than against source code, if it is likely the issue within the source code.

**Comment by Skulltrail192** [comment]
Seem fixed!
