### ISSUE TITLE
It says that it is a virus i need help

### ISSUE THREAD

**Issue by Tug1** [Skulltrail192/One-Core-Api#60]
its says this for me

![Screenshot 2023-05-06 210305](https://user-images.githubusercontent.com/97815724/236652561-fd57f659-a01f-42de-bb16-8720585998c7.png)
![Screenshot 2023-05-06 210345](https://user-images.githubusercontent.com/97815724/236652563-dcde6166-aa8a-4bc4-9ab8-97eeb7505d8b.png)

**Comment by TameemS** [comment]
False positive because it heavily modifies Windows XP. You'll be fine.

**Comment by Tug1** [comment]
Ok thanks
