### ISSUE TITLE
god this shit fucking sucks

### ISSUE THREAD

**Issue by Nicky20228** [Skulltrail192/One-Core-Api#63]
only logo retards and autistic children use this dumb retarded shit why does it exist

**Comment by NS-Clone** [comment]
> only logo retards and autistic children use this dumb retarded shit why does it exist

you always can do better %)

**Comment by jonm58** [comment]
@Skulltrail192 Can you close this issue?

**Comment by RUvlad1** [comment]
crazy

**Comment by Skulltrail192** [comment]
Closed by stupid and crazy behavior.
