### ISSUE TITLE
intel USB 3 driver on XP?

### ISSUE THREAD

**Issue by toddfraser88** [Skulltrail192/One-Core-Api#8]
can this be used to install the intel USB 3 driver on XP?

**Comment by blackwingcat** [comment]
I think One-Core-Api is not related to any drivers :3

**Comment by Skulltrail192** [comment]
However, i'm working about how port Windows 8 drivers or make my driver, based on Reactos.

**Comment by Skulltrail192** [comment]
Now it is possible: See forum win-raid Windows XP in modern parts. And see ntoskrnl ext_emu project

**Comment by Skulltrail192** [comment]
It is done on version 3.0.0. Please see One-Core-API Driver Update installer.

https://github.com/Skulltrail192/One-Core-API-Binaries/tree/master/Packages/x86/Driver%20Installer
