### ISSUE TITLE
Has One-core-API went into the future?

### ISSUE THREAD

**Issue by HBelusca** [Skulltrail192/One-Core-Api#9]
The project's README mentions that the layer is based on "ReactOS 3.x", while currently the ReactOS project is, to my knowledge, only at version 0.4.7 at the time of reporting this issue.
Any thoughts about that? Have we discovered the secrets of time travelling?

**Comment by Svyatpro** [comment]
It was a typo

**Comment by Skulltrail192** [comment]
Now, the base code is 0.4.x,  and i have plan to turn one-core-api compatible with reactos and help they.

**Comment by Svyatpro** [comment]
One-Core-API may hugely help ReactOS to switch to NT6.x because we test and fix NT6 API implementations on XP/2003.

**Comment by smallpotato000** [comment]
Seems that one-core-api replaced ntoskrnl.exe with the ReactOS kernel. Is this true?
And if so, we can drop WRKRazzle (and NTOSBE) completely?

**Comment by Skulltrail192** [comment]
Well, it almost done
